# Site settings
title: Hussein Faara
description: >- # this means to ignore newlines until "baseurl:"
 “Programs must be written for people to read, and only incidentally 
 for machines to execute.”  ― Harold Abelson
baseurl: ""  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: YoussefRaafatNasry/portfolYOU


# Build settings
markdown: kramdown
remote_theme: YoussefRaafatNasry/portfolYOU
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Hussein Faara
  image    : /assets/cv_image.jpg
  email    : faarahussein@gmail.com
  github   : hfaara18
  linkedin : hussein-faara-a6314b102/
  facebook : hussein.faara


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
- docs/docs.md
- docs/github.md
- docs/elements.md
- _projects/z-project.md
